/**
 * One-time generator for the NATS decentralized-auth identities.
 *
 * Run with `bun packages/nats-server/scripts/gen-nats-identities.ts`. It mints a
 * fresh operator, a SYS account, and an APP account (with a dedicated signing
 * key) and prints:
 *
 *   1. the `operator` / `system_account` / `resolver` / `resolver_preload` block
 *      to paste into `packages/nats-server/nats-server.conf` (all PUBLIC, since
 *      the JWTs contain only public keys and are safe to commit), and
 *   2. the APP account **signing key seed** (the one real secret) and the APP
 *      account identity public key, to store in each environment's
 *      `secrets.yaml` (`NATS_ACCOUNT_SIGNING_SEED`) and `wrangler.jsonc`
 *      (`NATS_ACCOUNT_ID`) respectively.
 *
 * Re-running rotates every key. That is the rotation procedure: regenerate,
 * paste the new block into the config, replace the secret, then redeploy BOTH
 * `nats` (new config) and `landing` (new signing seed) together. The operator
 * and account **identity** seeds are intentionally not persisted anywhere; only
 * the signing key is, which is all the Worker needs and the only key that has to
 * touch a running service.
 *
 * The JWT encoder here is deliberately a small standalone copy of the same
 * ed25519-nkey JWT format the landing Worker mints user tokens with
 * (packages/landing/worker/nats-jwt.ts). This script and that Worker are
 * separate deploy units (@zbc/nats-server vs @zbc/landing), so keeping this
 * one-time build tool free of a cross-package import is worth the handful of
 * duplicated lines (b64url + encode/sign).
 */
import * as nkeys from 'nkeys.js'

type KeyPair = ReturnType<typeof nkeys.createAccount>

function b64url(bytes: Uint8Array): string {
  let s = ''
  for (const b of bytes) s += String.fromCharCode(b)
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function b64urlJson(value: unknown): string {
  return b64url(new TextEncoder().encode(JSON.stringify(value)))
}

/** A unique token id. nats-server ignores `jti`, so any collision-free string works. */
function newJti(): string {
  const bytes = new Uint8Array(20)
  crypto.getRandomValues(bytes)
  return b64url(bytes)
}

/** Encode + sign a NATS JWT (v2) with the issuer keypair. */
function encodeJwt(claims: Record<string, unknown>, signer: KeyPair): string {
  const header = b64urlJson({ typ: 'JWT', alg: 'ed25519-nkey' })
  const payload = b64urlJson(claims)
  const sig = signer.sign(new TextEncoder().encode(`${header}.${payload}`))
  return `${header}.${payload}.${b64url(sig)}`
}

const now = () => Math.floor(Date.now() / 1000)

// Generous account limits, since this is a demo bus, not a metered tenant.
const accountLimits = {
  subs: -1,
  data: -1,
  payload: -1,
  imports: -1,
  exports: -1,
  wildcards: true,
  conn: -1,
  leaf: -1,
  disallow_bearer: false,
}

const operator = nkeys.createOperator()
const sysAccount = nkeys.createAccount()
const appAccount = nkeys.createAccount()
const appSigningKey = nkeys.createAccount()

const operatorPub = operator.getPublicKey()
const sysPub = sysAccount.getPublicKey()
const appPub = appAccount.getPublicKey()
const appSigningPub = appSigningKey.getPublicKey()

const operatorJwt = encodeJwt(
  {
    jti: newJti(),
    iat: now(),
    iss: operatorPub,
    name: 'zbc-operator',
    sub: operatorPub,
    nats: { type: 'operator', version: 2 },
  },
  operator,
)

const sysJwt = encodeJwt(
  {
    jti: newJti(),
    iat: now(),
    iss: operatorPub,
    name: 'SYS',
    sub: sysPub,
    nats: { type: 'account', version: 2, limits: accountLimits },
  },
  operator,
)

const appJwt = encodeJwt(
  {
    jti: newJti(),
    iat: now(),
    iss: operatorPub,
    name: 'APP',
    sub: appPub,
    nats: {
      type: 'account',
      version: 2,
      signing_keys: [appSigningPub],
      limits: accountLimits,
    },
  },
  operator,
)

const signingSeed = new TextDecoder().decode(appSigningKey.getSeed())

const configBlock = `# --- decentralized auth (generated by scripts/gen-nats-identities.ts) ---
# All three JWTs below are PUBLIC (they carry only public keys, operator-signed)
# and are safe to commit. The account signing seed that mints user tokens is NOT
# here; it lives only in each environment's secrets.yaml as
# NATS_ACCOUNT_SIGNING_SEED, held by the landing Worker.
operator: ${operatorJwt}
system_account: ${sysPub}
resolver: MEMORY
resolver_preload: {
  ${sysPub}: ${sysJwt}
  ${appPub}: ${appJwt}
}`

console.log(configBlock)
console.log('\n# --- secrets (do NOT commit these two lines) ---')
console.log(`NATS_ACCOUNT_SIGNING_SEED=${signingSeed}`)
console.log(`NATS_ACCOUNT_ID=${appPub}   # public, goes in wrangler.jsonc vars`)
