CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:Kj3Mt+QnV7J+gQRfS73l6GxFWeHOnwrMJ85J0o4ztiLcydROMUhSCKpj3ezj2wQoEZcTKn4=,iv:nTpIXhWF8wo3G7M8koSttiH4flqYS2JFIxUSzfZRbaM=,tag:7DDCBZw970dPgbXQ9U91hQ==,type:str]
NATS_ACCOUNT_SIGNING_SEED: ENC[AES256_GCM,data:W/pgQIkoJamUgrIEOi5puBy4t3yvSLaZ1QPvUbsd3uKJuQPYoju9ifGF0vzYBEkJf8Xq8Vp3fSPhIw==,iv:ujxnhRW+koc3lA1b9Kt/TU3+jkZKuZ+pwlMwfZkN0Sc=,tag:W22433ZE8zaAj4yY8UE1FQ==,type:str]
INBOX_TOKEN: ENC[AES256_GCM,data:IzIhCi8mm8nzD37cDgzyZuOApIZdFa0Z7a5/DgMMcYHODzh4NcCPBrY9OALBcLZvyrfOWtL603I2TCCHVmzz5Q==,iv:XEVb+/iT8onGiSVFTm1cPdYXoavGhkyfbIp8dpERHcc=,tag:mavAkpi7QkPB7kdxwvog0w==,type:str]
WAREHOUSE_TOKEN: ENC[AES256_GCM,data:vAR+JnFw6DFz/PckF3kDYmFbrHgQ43ErdMp+qhEv5BVmU63AHhLMCmvHet4U4Fxbl3lSMgJomTGv+pbgI6f2lQ==,iv:o6GJCdzDGajlS6mmwreFcrjZfQuCXj1HtPW5epuD+fI=,tag:kCDHJlIzh7GQ2Y4xIKXqow==,type:str]
GITHUB_TOKEN: ENC[AES256_GCM,data:SFgL+ly3aqc9Y235WzWcm1FSpS354w26Ze6wIi3f9xAwK0wZF+X8fA==,iv:4nZn11mgaPKCQec21WMazNyiUdDApcOPh5E6pyBonlg=,tag:XaZOEliwbpbBJaEgVZnqyQ==,type:str]
WAREHOUSE_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:znOdtK9O8OtKSv46/k1Yqb48xYSvqu93iXXIhT1VVuc=,iv:UORe4tz0C1n6lrtyCItbsIW6j63fMcg2xAaCrr9xs4c=,tag:vwMuL3gPcy9OWq4e5G+28g==,type:str]
WAREHOUSE_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mOBCYK6Lv00tJlNpSXEaOMbrKSy8tT80uPcwb9oRUGz/HRXR9CiZEUqWQUseHCwyOcWMUTqZ1T2OoXLA7hhn0Q==,iv:wQaCZWGRGkjboBGZio48Yq6OhoqR4Ehak/zD53Fj+LA=,tag:KLhfHNQJzHfKJTQtygrLyA==,type:str]
sops:
    age:
        - recipient: age1aw8yfxfkug204rkcjcwsqpmlf8ne8cr645hw8pf8ur8085gru42qmns0xw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicWZVU1FZYWI5MHJXTkFy
            NUs1MWVUdCtRZTk4c0R2djl5UW1lWGNjR0I4CmFMcFh0TG9YUkgzYysxQy90UHJ1
            NHBlM1ZUdm9ubnNGZVIvaytEeTh1VncKLS0tIDM5SG5OdHlxMUlvNEtWdFJvOTY4
            T0tnKzM4c0lPS1FjTlpyVXNIWU4yMWsK18nSWnDmN3eTtruoEjW+Rsib4DhkBg/+
            JUmQ8qwfLF+eZBnYc+9yEh6gzefQnp/1mcSqJNZEl/iRSXKLXlr2xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2Mwam03Y2hqNlpZWHlZ
            YlRRSGhZV1FrY21ndDB0WHRmTkZQRjVBalE4CjQvcnlyVjNUQWlMay9QQ0wvaDkw
            WjR5RE5CeTNrRU8yWHlZSERGMCtZR1UKLS0tIENQR3dnRm4xd3ZyUllUcllFeWNa
            RU1KYXpmdzNpLzB6WjZ0N2hCdVo4NU0KbiyJF+VSp/EBYvSUVTnh12p3Ujbdq9tt
            htkXUdSanVl0q6H0QHZh0oeUyzWXZNXjbvRsRqJG+TlaiJ63GJSkcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10j9e36excydmzmwgs7n5lpcte89s5se67842dwymrv72dncu755s8d82tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFBhY3hSdC9LbnZQekVv
            aXJUTVhFSVFFdWoxNUxRN0ZDNlk0Wjk2VFh3CjZoSmpkWUdJY2t1TVA2VnZCWFhn
            eXJoT0hhNDNmTGhBek92K0k4ZUNrN1EKLS0tIHNDTWVnZG5kWjBwOHBjV1c5TlZB
            MUpYZVZQZUpaMnZYM3RkWmFMNDVLQVkKNYbqg0d4eWGZTsFpJyR3ihhqUzjpXkNk
            6O6MoMRvzIsoey57l/VpNL2TqK9ptt0g+t5q62I5hy7cYiTjplAXUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age125sdujhaks4ezxrk9p4uaxmhmqau0rwqwv0dtc6qal4vl8xuav4sgrfvdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK1BRaURSUHN5T3pzck90
            NHE3b3RvSjRySWU0a3pOWWFlWFlDWDFpQXlzCmZMK0Myay9NVjdXTTJ6cDMycTFX
            WHY1dEkrMFFjR2xiNHNYTnhpcjErWWcKLS0tIHFwQWxGaWRXbFJWOXVrcjk3cldN
            THY4enpTc3FTbWFEM0lFK2lIVGtsdUUKxYSPPdOqTIKrjYHNMXVe/Ot9LHPUJxx1
            Uoe4PM2EcmTcCQqRUE9EAFl7agq3v/W9OIYkaEUkUGUk8Dd9EuPVpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T04:17:27Z"
    mac: ENC[AES256_GCM,data:VIqWpGNRndS7JEctYPJzrTSx+DDrdzaLvprf8EZOnMp8qC6a3MtOhlFrceahR5cEQKsyZMQAEoyR8XuEiV10+l4LsouEylHbSK1umGjt3Z4BEt090iOzkY7JTRb+LHW4/UUEXKyAQEMbSPqbBDsGqsO21RDWaoyRi1Urs88cpUk=,iv:/2XvEubZVhxRvZKemPo2+fMgSM+Z1pw5tzt7hHs2OhA=,tag:lQnN5/Ivk8iTAzxT2zlqsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
