creation_rules:
  - age: >-
      age1aw8yfxfkug204rkcjcwsqpmlf8ne8cr645hw8pf8ur8085gru42qmns0xw,
      age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j,
      age1tw53mfrjzs5pk4w3wu5zd90qewkep8atgehdf5hlnjct2ygu6p0q9vrjwe
