/**
 * E2E crypto for Secret Requests (ADR-0003): the CLI generates an ephemeral
 * ECDH P-256 keypair per Channel; the public key travels only in the URL
 * fragment. The browser generates its own ephemeral pair, derives an AES-GCM
 * key via ECDH, and encrypts. The relay only ever sees `SubmissionPayload`
 * ciphertext. WebCrypto-only — runs identically in browsers, workerd, and Bun.
 */

export interface SubmissionPayload {
  /** Browser's ephemeral public key (raw P-256 point, base64url) */
  epk: string
  /** AES-GCM IV (base64url) */
  iv: string
  /** Ciphertext (base64url) */
  ct: string
}

function toB64url(buf: ArrayBuffer | Uint8Array): string {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf)
  let bin = ''
  for (const b of bytes) bin += String.fromCharCode(b)
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function fromB64url(s: string): Uint8Array {
  const bin = atob(s.replace(/-/g, '+').replace(/_/g, '/'))
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}

const ECDH = { name: 'ECDH', namedCurve: 'P-256' } as const

export async function generateChannelKeypair(): Promise<{
  publicKeyB64: string
  privateKey: CryptoKey
}> {
  const pair = await crypto.subtle.generateKey(ECDH, false, ['deriveKey'])
  const raw = await crypto.subtle.exportKey('raw', pair.publicKey)
  return { publicKeyB64: toB64url(raw), privateKey: pair.privateKey }
}

async function deriveAesKey(privateKey: CryptoKey, peerPublicRaw: Uint8Array): Promise<CryptoKey> {
  const peer = await crypto.subtle.importKey('raw', peerPublicRaw as BufferSource, ECDH, false, [])
  return crypto.subtle.deriveKey(
    { name: 'ECDH', public: peer },
    privateKey,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt'],
  )
}

/** Browser side: encrypt `plaintext` to the channel's public key. */
export async function encryptForChannel(
  channelPublicKeyB64: string,
  plaintext: string,
): Promise<SubmissionPayload> {
  const pair = await crypto.subtle.generateKey(ECDH, false, ['deriveKey'])
  const aes = await deriveAesKey(pair.privateKey, fromB64url(channelPublicKeyB64))
  const iv = crypto.getRandomValues(new Uint8Array(12))
  const ct = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    aes,
    new TextEncoder().encode(plaintext),
  )
  const epk = await crypto.subtle.exportKey('raw', pair.publicKey)
  return { epk: toB64url(epk), iv: toB64url(iv), ct: toB64url(ct) }
}

export interface EncryptedDocument {
  /** AES-GCM IV (base64url) */
  iv: string
  /** Ciphertext (base64url) */
  ct: string
}

/**
 * Editor mode carries the document CLI→browser and back, so both ends need
 * the same key: a symmetric AES-GCM key generated by the CLI and carried in
 * the URL fragment (never sent to the server), mirroring the ECDH flow's
 * fragment discipline.
 */
export async function generateDocumentKey(): Promise<string> {
  return toB64url(crypto.getRandomValues(new Uint8Array(32)))
}

async function importDocumentKey(keyB64: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('raw', fromB64url(keyB64) as BufferSource, 'AES-GCM', false, [
    'encrypt',
    'decrypt',
  ])
}

export async function encryptWithDocumentKey(
  keyB64: string,
  plaintext: string,
): Promise<EncryptedDocument> {
  const key = await importDocumentKey(keyB64)
  const iv = crypto.getRandomValues(new Uint8Array(12))
  const ct = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    new TextEncoder().encode(plaintext),
  )
  return { iv: toB64url(iv), ct: toB64url(ct) }
}

export async function decryptWithDocumentKey(
  keyB64: string,
  doc: EncryptedDocument,
): Promise<string> {
  const key = await importDocumentKey(keyB64)
  const pt = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: fromB64url(doc.iv) as BufferSource },
    key,
    fromB64url(doc.ct) as BufferSource,
  )
  return new TextDecoder().decode(pt)
}

/**
 * Short human-checkable code derived from the channel public key. The CLI
 * prints it; the page derives the same from the URL fragment. A visual match
 * confirms the human is answering the request they think they are.
 * Alphabet omits 0/O/1/I to stay unambiguous when read aloud.
 */
export async function pairingCode(channelPublicKeyB64: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    'SHA-256',
    fromB64url(channelPublicKeyB64) as BufferSource,
  )
  const bytes = new Uint8Array(digest)
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  const chars = Array.from({ length: 4 }, (_, i) => alphabet[(bytes[i] ?? 0) % alphabet.length])
  return `${chars[0]}${chars[1]}-${chars[2]}${chars[3]}`
}

/** CLI side: decrypt a browser submission with the channel's private key. */
export async function decryptSubmission(
  privateKey: CryptoKey,
  payload: SubmissionPayload,
): Promise<string> {
  const aes = await deriveAesKey(privateKey, fromB64url(payload.epk))
  const pt = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: fromB64url(payload.iv) as BufferSource },
    aes,
    fromB64url(payload.ct) as BufferSource,
  )
  return new TextDecoder().decode(pt)
}
