/**
 * Mint short-lived, per-session NATS **user JWTs** (ed25519-nkey, v2) from the
 * APP account signing key. Runs inside the Cloudflare Worker — the signing seed
 * never leaves it; only the minted token reaches the browser.
 *
 * The token is a bearer token (`bearer_token: true`): the client authenticates
 * with the JWT alone and needs no user NKey seed of its own. It is scoped to a
 * single subject prefix for both publish and subscribe, carries a short expiry,
 * and is restricted to WebSocket connections. See the operator/account material
 * baked into packages/nats-server/nats-server.conf, generated by
 * packages/nats-server/scripts/gen-nats-identities.ts.
 */
import * as nkeys from 'nkeys.js'

const B32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'

/** RFC 4648 base32, uppercase, no padding — the encoding NATS uses for `jti`. */
function base32(bytes: Uint8Array): string {
  let bits = 0
  let value = 0
  let out = ''
  for (const b of bytes) {
    value = (value << 8) | b
    bits += 8
    while (bits >= 5) {
      out += B32[(value >>> (bits - 5)) & 31]
      bits -= 5
    }
  }
  if (bits > 0) out += B32[(value << (5 - bits)) & 31]
  return out
}

function b64url(bytes: Uint8Array): string {
  let s = ''
  for (const b of bytes) s += String.fromCharCode(b)
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function b64urlJson(value: unknown): string {
  return b64url(new TextEncoder().encode(JSON.stringify(value)))
}

function newJti(): string {
  const bytes = new Uint8Array(20)
  crypto.getRandomValues(bytes)
  return base32(bytes)
}

export type MintOptions = {
  /** APP account signing-key seed (SA...), the Worker's one secret. */
  signingSeed: string
  /** APP account identity public key (A...), for `issuer_account`. */
  accountId: string
  /** Subject prefix this token may publish/subscribe on, e.g. `landing.cursors.>`. */
  subject: string
  /** Token lifetime in seconds. */
  ttlSeconds: number
  /** Human-readable connection name embedded in the JWT. */
  name?: string
}

/**
 * Mint a bearer user JWT. Returns just the JWT string — the client passes it to
 * `jwtAuthenticator(jwt)` with no seed.
 */
export function mintUserJwt(opts: MintOptions): string {
  const signer = nkeys.fromSeed(new TextEncoder().encode(opts.signingSeed))
  // A fresh ephemeral user identity per session. Bearer means its seed is never
  // needed, so we generate the public key and discard the private half.
  const user = nkeys.createUser()

  const now = Math.floor(Date.now() / 1000)
  const claims = {
    jti: newJti(),
    iat: now,
    exp: now + opts.ttlSeconds,
    iss: signer.getPublicKey(),
    name: opts.name ?? 'landing',
    sub: user.getPublicKey(),
    nats: {
      issuer_account: opts.accountId,
      pub: { allow: [opts.subject] },
      sub: { allow: [opts.subject] },
      subs: -1,
      data: -1,
      payload: -1,
      bearer_token: true,
      allowed_connection_types: ['WEBSOCKET'],
      type: 'user',
      version: 2,
    },
  }

  const header = b64urlJson({ typ: 'JWT', alg: 'ed25519-nkey' })
  const payload = b64urlJson(claims)
  const sig = signer.sign(new TextEncoder().encode(`${header}.${payload}`))
  return `${header}.${payload}.${b64url(sig)}`
}
